import { useEffect, useState, type FormEvent } from 'react';
import { ArrowUpRight, Check, Globe2, Moon, Sun, Menu, X } from 'lucide-react';
import { z } from 'zod';
import { Button } from './components/ui/Button';
import { Card } from './components/ui/Card';
import { Input } from './components/ui/Input';
import { Badge } from './components/ui/Badge';
import { Dialog } from './components/ui/Dialog';
import { Tabs } from './components/ui/Tabs';
import { Accordion } from './components/ui/Accordion';
import { useI18n, useTheme } from './contexts';

const contactSchema = z.object({ name: z.string().min(2), email: z.string().email(), message: z.string().min(10) });
const projects = [
  { id:'01', title:'Tidal Commons', type:'Civic / 2025', text:'A flood-resilient library that turns a Rotterdam water basin into a public room.', image:'https://images.unsplash.com/photo-1487958449943-2429e8be8625?auto=format&fit=crop&w=1200&q=85' },
  { id:'02', title:'Afterlight Market', type:'Retail / 2024', text:'A nocturnal food hall calibrated to the thermal rhythm of a desert city.', image:'https://images.unsplash.com/photo-1497366811353-6870744d04b2?auto=format&fit=crop&w=1200&q=85' },
  { id:'03', title:'Moss / 17', type:'Material study / 2023', text:'Seventeen prototypes for a facade that grows its own shade.', image:'https://images.unsplash.com/photo-1531058020387-3be344556be6?auto=format&fit=crop&w=1200&q=85' }
];
const faqs = [{q:'What scale do you work at?',a:'From a single threshold to a whole district. The common thread is making climate visible, useful, and beautiful.'},{q:'Do you collaborate with studios?',a:'Always. I bring the spatial direction and invite engineers, artists, ecologists, and local voices into the room early.'},{q:'Where are you available?',a:'Rotterdam is home base. Current work stretches from Tangier to Taipei, with remote workshops and short field residencies.'}];

export default function App() {
  const { theme, toggle } = useTheme(); const { locale, setLocale } = useI18n(); const [active, setActive] = useState('home'); const [menu, setMenu] = useState(false); const [selected, setSelected] = useState<typeof projects[0] | null>(null); const [sent, setSent] = useState(false); const [error, setError] = useState('');
  useEffect(() => { const observer = new IntersectionObserver(entries => entries.forEach(entry => entry.isIntersecting && setActive(entry.target.id)), { rootMargin:'-35% 0px -55% 0px' }); document.querySelectorAll('section[id]').forEach(section => observer.observe(section)); return () => observer.disconnect(); }, []);
  function submit(event: FormEvent<HTMLFormElement>) { event.preventDefault(); const data = Object.fromEntries(new FormData(event.currentTarget)); const result = contactSchema.safeParse(data); if (!result.success) { setError('Please add your name, a valid email, and a little more detail.'); return; } setError(''); setSent(true); event.currentTarget.reset(); }
  const nav = [{id:'home',label:'Index'},{id:'about',label:'Approach'},{id:'work',label:'Selected work'},{id:'contact',label:'Contact'}];
  return <main className="grain min-h-screen overflow-hidden bg-paper text-ink">
    <header className="fixed left-0 right-0 top-0 z-40 px-5 py-4 md:px-10"><nav className="mx-auto flex max-w-7xl items-center justify-between rounded-full border border-ink/20 bg-paper/80 px-5 py-3 backdrop-blur-xl"><a href="#home" className="display text-xl font-bold tracking-tight">MV<span className="text-ember">.</span></a><div className="hidden items-center gap-6 md:flex">{nav.map(item => <a key={item.id} href={`#${item.id}`} className={`text-[10px] font-bold uppercase tracking-[.18em] transition hover:text-ember ${active === item.id ? 'text-ember' : 'opacity-65'}`}>{item.label}</a>)}</div><div className="flex items-center gap-2"><button aria-label="Toggle language" onClick={() => setLocale(locale === 'en' ? 'ar' : 'en')} className="rounded-full p-2 hover:bg-ink/10"><Globe2 size={16}/><span className="sr-only">{locale}</span></button><button aria-label="Toggle theme" onClick={toggle} className="rounded-full p-2 hover:bg-ink/10">{theme === 'dark' ? <Sun size={16}/> : <Moon size={16}/>}</button><button className="p-2 md:hidden" onClick={() => setMenu(!menu)}>{menu ? <X size={18}/> : <Menu size={18}/>}</button></div></nav>{menu && <div className="mx-5 mt-2 rounded-2xl border border-ink/20 bg-paper p-5 md:hidden">{nav.map(item => <a onClick={() => setMenu(false)} key={item.id} href={`#${item.id}`} className="block border-b border-ink/10 py-3 text-sm font-bold">{item.label}</a>)}</div>}</header>
    <section id="home" className="relative mx-auto grid min-h-screen max-w-7xl items-center gap-10 px-6 pb-16 pt-36 md:grid-cols-[1.15fr_.85fr] md:px-10"><div className="reveal relative z-10"><Badge>Spatial architect / 1989—</Badge><h1 className="display mt-7 max-w-4xl text-[clamp(4.5rem,12vw,11rem)] leading-[.78] tracking-[-.07em]">Rooms that<br/><i className="font-normal text-ember">remember</i><br/>tomorrow.</h1><div className="mt-10 flex max-w-md items-start gap-5"><span className="mt-2 h-px w-12 bg-ember"/><p className="text-sm leading-7 opacity-70">Mara Voss builds civic spaces for a hotter, wetter, more beautifully complicated world.</p></div></div><div className="relative mx-auto aspect-[4/5] w-full max-w-md rotate-2 bg-ember p-3 shadow-2xl"><div className="h-full overflow-hidden bg-ink"><img className="h-full w-full object-cover opacity-80 mix-blend-screen" src="https://images.unsplash.com/photo-1511818966892-d7d671e672a2?auto=format&fit=crop&w=900&q=85" alt="Geometric concrete architecture"/><div className="absolute bottom-8 left-8 text-paper"><div className="display text-5xl">37°N</div><div className="text-[10px] uppercase tracking-[.3em]">latitude of attention</div></div></div><div className="absolute -right-10 -top-8 orbit rounded-full border border-ink/40 p-3"><div className="h-16 w-16 rounded-full border border-ink/40"/></div></div><div className="absolute bottom-8 left-6 text-[10px] uppercase tracking-[.2em] opacity-50 md:left-10">A practice for the in-between</div></section>
    <section id="about" className="mx-auto max-w-7xl px-6 py-28 md:px-10"><div className="grid gap-12 md:grid-cols-[.7fr_1.3fr]"><div><p className="text-xs font-bold uppercase tracking-[.3em] text-ember">02 / Approach</p><h2 className="display mt-5 text-6xl leading-none">The weather<br/><i>is in the room.</i></h2></div><div className="max-w-2xl pt-8 text-lg leading-8 opacity-75"><p>I work where architecture meets evidence: heat maps, migration stories, shadow studies, the sound of a market at 6:14am. Every project starts with a question, not a shape.</p><p className="mt-6">The result is a grounded kind of futurism — structures that do more than stand still. They collect rain, host rituals, make room for strangers, and give a neighborhood a longer afternoon.</p><div className="mt-10 grid grid-cols-2 gap-4 border-t border-ink/20 pt-6 text-sm"><div><b className="display text-4xl text-ember">14</b><br/>built interventions</div><div><b className="display text-4xl text-ember">09</b><br/>cities listening</div></div></div></div></section>
    <section className="bg-ink py-24 text-paper"><div className="mx-auto max-w-7xl px-6 md:px-10"><div className="mb-12 flex items-end justify-between"><div><p className="text-xs font-bold uppercase tracking-[.3em] text-ember">03 / Field notes</p><h2 className="display mt-4 text-6xl">How I look.</h2></div><span className="hidden text-xs opacity-50 md:block">Scroll / observe / adjust</span></div><Tabs items={[{label:'Material',content:<div className="grid gap-8 md:grid-cols-3"><Card className="border-paper/20 bg-paper/5 p-7"><div className="mb-12 text-5xl text-ember">01</div><h3 className="display text-3xl">Feel first</h3><p className="mt-4 text-sm leading-6 opacity-60">Materials are climate instruments. Stone stores coolness. Fabric catches wind. Moss writes time onto a wall.</p></Card><Card className="border-paper/20 bg-paper/5 p-7"><div className="mb-12 text-5xl text-ember">02</div><h3 className="display text-3xl">Measure twice</h3><p className="mt-4 text-sm leading-6 opacity-60">Data is not decoration. It gives intuition a second pair of eyes and makes a decision legible to everyone.</p></Card><Card className="border-paper/20 bg-paper/5 p-7"><div className="mb-12 text-5xl text-ember">03</div><h3 className="display text-3xl">Leave room</h3><p className="mt-4 text-sm leading-6 opacity-60">The most generous detail is an unfinished edge: somewhere for a child, a plant, or a new ritual to begin.</p></Card></div>},{label:'Tools',content:<div className="grid gap-4 md:grid-cols-2"><p className="display text-4xl">Rhino / Grasshopper / QGIS / Archicad / clay / field recorder / one very sharp pencil.</p><p className="max-w-sm text-sm leading-7 opacity-60">A deliberately porous toolkit. Digital precision enters the room, but never gets the final word.</p></div>},{label:'Belief',content:<div className="max-w-3xl"><p className="display text-5xl leading-tight">“A public building should make you feel more possible when you leave it.”</p></div>}]}/></div></section>
    <section id="work" className="mx-auto max-w-7xl px-6 py-28 md:px-10"><div className="mb-14 flex flex-col justify-between gap-5 md:flex-row md:items-end"><div><p className="text-xs font-bold uppercase tracking-[.3em] text-ember">04 / Selected work</p><h2 className="display mt-4 text-7xl leading-none">Proof of<br/><i>weather.</i></h2></div><p className="max-w-xs text-sm leading-6 opacity-60">Three built arguments for paying closer attention to the sky above us.</p></div><div className="grid gap-7 md:grid-cols-12">{projects.map((project,index) => <button key={project.id} onClick={() => setSelected(project)} className={`group text-left md:col-span-${index === 1 ? '7' : '5'} ${index === 1 ? 'md:mt-24' : ''}`}><div className="relative aspect-[4/3] overflow-hidden bg-ink"><img src={project.image} alt={project.title} className="h-full w-full object-cover grayscale transition duration-700 group-hover:scale-105 group-hover:grayscale-0"/><span className="absolute left-4 top-4 rounded-full bg-paper px-3 py-1 text-xs font-bold text-ink">{project.id}</span><span className="absolute bottom-4 right-4 grid h-11 w-11 place-items-center rounded-full bg-ember text-paper opacity-0 transition group-hover:opacity-100"><ArrowUpRight size={18}/></span></div><div className="mt-4 flex justify-between gap-4"><div><h3 className="display text-3xl">{project.title}</h3><p className="mt-1 max-w-sm text-sm opacity-60">{project.text}</p></div><span className="pt-2 text-[10px] font-bold uppercase tracking-widest text-ember">{project.type}</span></div></button>)}</div></section>
    <section className="border-y border-ink/15 bg-ember px-6 py-24 text-paper md:px-10"><div className="mx-auto grid max-w-7xl gap-12 md:grid-cols-[1fr_1fr]"><div><p className="text-xs font-bold uppercase tracking-[.3em]">05 / In practice</p><h2 className="display mt-5 text-7xl leading-[.85]">A small<br/><i>radical</i><br/>practice.</h2></div><div className="space-y-8 text-sm"><div className="border-t border-paper/40 pt-4"><span className="opacity-60">2021—now</span><h3 className="mt-2 text-xl font-bold">Independent practice / Rotterdam</h3><p className="mt-2 max-w-md opacity-75">Spatial direction, public commissions, and temporary structures with a long afterlife.</p></div><div className="border-t border-paper/40 pt-4"><span className="opacity-60">2016—2021</span><h3 className="mt-2 text-xl font-bold">Atelier North / Copenhagen</h3><p className="mt-2 max-w-md opacity-75">Senior architect across resilient housing and coastal infrastructure.</p></div><div className="border-t border-paper/40 pt-4"><span className="opacity-60">2012—2016</span><h3 className="mt-2 text-xl font-bold">TU Delft / M.Arch</h3><p className="mt-2 max-w-md opacity-75">Graduated with a thesis on shade as a social resource.</p></div></div></div></section>
    <section className="mx-auto max-w-7xl px-6 py-28 md:px-10"><div className="grid gap-12 md:grid-cols-[.8fr_1.2fr]"><div><p className="text-xs font-bold uppercase tracking-[.3em] text-ember">06 / Kind words</p><p className="display mt-5 text-5xl leading-tight">“She makes the invisible feel like a place you can visit.”</p><p className="mt-6 text-xs font-bold uppercase tracking-widest opacity-60">— Noor El-Khatib, curator</p></div><div className="pt-2"><Accordion items={faqs}/></div></div></section>
    <section id="contact" className="bg-ink px-6 py-24 text-paper md:px-10"><div className="mx-auto grid max-w-7xl gap-16 md:grid-cols-[1fr_.9fr]"><div><p className="text-xs font-bold uppercase tracking-[.3em] text-ember">07 / Make contact</p><h2 className="display mt-6 text-7xl leading-[.85]">Bring me<br/><i>the difficult</i><br/>brief.</h2><a href="mailto:studio@maravoss.space" className="mt-10 inline-block border-b border-ember pb-2 text-sm text-ember">studio@maravoss.space</a></div><form onSubmit={submit} className="space-y-5"><Input name="name" placeholder="Your name" aria-label="Your name" required className="border-paper/30 text-paper placeholder:text-paper/40"/><Input name="email" type="email" placeholder="Email address" aria-label="Email address" required className="border-paper/30 text-paper placeholder:text-paper/40"/><textarea name="message" placeholder="What are we making room for?" aria-label="Message" required className="min-h-32 w-full rounded-xl border border-paper/30 bg-transparent px-4 py-3 outline-none focus:border-ember"/><Button className="bg-ember text-paper">Send the signal <ArrowUpRight className="ml-2" size={16}/></Button>{error && <p className="text-sm text-ember">{error}</p>}{sent && <p className="flex items-center gap-2 text-sm text-emerald-400"><Check size={16}/> Message received. I’ll be in touch soon.</p>}</form></div><footer className="mx-auto mt-24 flex max-w-7xl flex-col justify-between gap-4 border-t border-paper/20 pt-6 text-[10px] uppercase tracking-[.2em] opacity-50 md:flex-row"><span>© 2026 Mara Voss Studio</span><span>Rotterdam / everywhere</span><a href="#home">Back to top ↑</a></footer></section>
    <Dialog open={selected !== null} onClose={() => setSelected(null)}>{selected && <><Badge>{selected.type}</Badge><h2 className="display mt-5 text-5xl">{selected.title}</h2><p className="mt-5 leading-7 opacity-70">{selected.text} This project began as a series of walks through the site, collecting temperature readings, overheard fragments, and shadows. The final structure is an invitation to stay longer.</p><Button onClick={() => setSelected(null)} className="mt-7 bg-ink text-paper">Close</Button></>}</Dialog>
  </main>;
}